import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import { themes as prismThemes } from 'prism-react-renderer';

const config: Config = {
  title: 'Open — A to Z Computer Science',
  tagline:
    'An open learning hub — from programming fundamentals to Machine Learning, Deep Learning, Generative AI and Computer Vision.',
  favicon: 'img/favicon.svg',

  // ---- GitHub Pages ----
  url: 'https://subrata-cs.github.io',
  baseUrl: '/open/',
  organizationName: 'Subrata-CS',
  projectName: 'open',
  trailingSlash: false,
  deploymentBranch: 'gh-pages',

  onBrokenLinks: 'warn',
  onBrokenAnchors: 'warn',

  // Rspack-based faster build (much quicker across 620+ pages)
  future: {
    v4: true,
    faster: true,
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },
  themes: [
    '@docusaurus/theme-mermaid',
    [
      // Offline full-text search — GitHub Pages e kaj kore, kono API key lagbe na
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: '/docs',
        highlightSearchTermsOnTargetPage: true,
        explicitSearchResultPath: true,
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'docs',
          routeBasePath: 'docs',
          // sidebars.ts uses autogenerated mode -> the sidebar is built by scanning docs/
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/Subrata-CS/open/edit/main/',
          // Edit affordances stay in the markup but are hidden from visitors
          // (see "owner mode" in src/theme/Root.tsx). No last-updated stamp.
          showLastUpdateTime: false,
          showLastUpdateAuthor: false,
          breadcrumbs: true,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/social-card.svg',
    // Dark only — no light theme, no toggle.
    colorMode: {
      defaultMode: 'dark',
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },
    docs: {
      sidebar: {
        hideable: true,
        autoCollapseCategories: true,
      },
    },
    navbar: {
      title: 'Open',
      logo: {
        alt: 'Open CS Hub',
        src: 'img/logo.svg',
      },
      hideOnScroll: true,
      items: [
        { to: '/', label: 'Home', position: 'left', activeBaseRegex: '^/open/$' },
        {
          type: 'docSidebar',
          sidebarId: 'csSidebar',
          position: 'left',
          label: 'Syllabus',
        },
        { to: '/docs', label: 'Start here', position: 'left' },
        { to: '/playground', label: 'Code Lab', position: 'left' },
        { to: '/apps', label: 'Test Yourself', position: 'left' },
        {
          // Opens the Ask AI drawer on the current page — no navigation, and
          // no API key, so nothing is ever billed to us.
          type: 'dropdown',
          label: 'Ask AI',
          position: 'left',
          className: 'navbar-ai',
          items: [
            // These open the in-page drawer (see src/theme/Root.tsx), so the
            // reader never leaves the page they are on.
            { to: '#ask-ai-chatgpt', label: 'ChatGPT', className: 'ai-item ai-chatgpt' },
            { to: '#ask-ai-claude', label: 'Claude', className: 'ai-item ai-claude' },
            {
              to: '#ask-ai-perplexity',
              label: 'Perplexity',
              className: 'ai-item ai-perplexity',
            },
          ],
        },
        {
          href: 'https://www.linkedin.com/in/sp4532/',
          position: 'right',
          className: 'header-linkedin-link',
          'aria-label': 'LinkedIn profile',
        },
        {
          href: 'https://github.com/Subrata-CS',
          position: 'right',
          className: 'header-github-link',
          'aria-label': 'GitHub profile',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [],
      copyright: `MIT License · © ${new Date().getFullYear()} Subrata Pramanik`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: [
        'bash',
        'c',
        'cpp',
        'java',
        'python',
        'sql',
        'json',
        'yaml',
        'rust',
        'go',
        'kotlin',
        'docker',
      ],
    },
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 4,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
