import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import { themes as prismThemes } from 'prism-react-renderer';

const config: Config = {
  title: 'Open â€” A to Z Computer Science',
  tagline:
    'An open learning hub â€” from programming fundamentals to Machine Learning, Deep Learning, Generative AI and Computer Vision.',
  favicon: 'img/favicon.svg',

  // ---- GitHub Pages ----
  url: 'https://subrata-cs.github.io',
  baseUrl: '/open/',
  organizationName: 'Subrata-CS',
  projectName: 'open',
  trailingSlash: false,
  deploymentBranch: 'gh-pages',

  onBrokenLinks: 'warn',
  onBrokenAnchors: 'warn',

  // Rspack-based faster build (much quicker across 620+ pages)
  future: {
    v4: true,
    faster: true,
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },
  /**
   * Security headers, declared in the document because GitHub Pages serves
   * static files and cannot set real HTTP headers.
   *
   * The policy is an allow-list: the only places the browser may fetch code,
   * styles or data from are the ones this site actually uses. Anything
   * injected by an attacker â€” an inline <script>, a hijacked third-party
   * domain, an iframe wrapping the site â€” is refused by the browser itself.
   *
   * `frame-ancestors` is deliberately absent: browsers ignore it in a <meta>
   * tag, and GitHub Pages cannot send it as a header, so declaring it would
   * only produce a console warning on every page and no protection.
   *
   * 'unsafe-eval' and 'wasm-unsafe-eval' are unavoidable here: Pyodide,
   * sql.js and the JavaScript sandbox all compile code at run time. That is
   * the whole point of the Code Lab. It stays contained because user code
   * only ever runs inside a Web Worker or a WebAssembly sandbox, never with
   * access to the page.
   */
  headTags: [
    {
      tagName: 'meta',
      attributes: {
        'http-equiv': 'Content-Security-Policy',
        content: [
          "default-src 'self'",
          "base-uri 'self'",
          "object-src 'none'",
          "form-action 'self'",
          "script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' blob: https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://esm.run",
          "worker-src 'self' blob:",
          "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
          "img-src 'self' data: blob: https:",
          "font-src 'self' data: https://fonts.gstatic.com",
          "connect-src 'self' blob: data: https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://esm.run https://wandbox.org https://countapi.mileshilliard.com https://huggingface.co https://raw.githubusercontent.com",
          "frame-src 'none'",
          "manifest-src 'self'",
          "upgrade-insecure-requests",
        ].join('; '),
      },
    },
    {
      tagName: 'meta',
      attributes: {
        name: 'referrer',
        content: 'strict-origin-when-cross-origin',
      },
    },
  ],

  themes: [
    '@docusaurus/theme-mermaid',
    [
      // Offline full-text search â€” GitHub Pages e kaj kore, kono API key lagbe na
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: '/docs',
        highlightSearchTermsOnTargetPage: true,
        explicitSearchResultPath: true,
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'docs',
          routeBasePath: 'docs',
          // sidebars.ts uses autogenerated mode -> the sidebar is built by scanning docs/
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/Subrata-CS/open/edit/main/',
          // Edit affordances stay in the markup but are hidden from visitors
          // (see "owner mode" in src/theme/Root.tsx). No last-updated stamp.
          showLastUpdateTime: false,
          showLastUpdateAuthor: false,
          breadcrumbs: true,
        },
        blog: false,
        theme: {
          customCss:  ['./src/css/custom.css', './src/css/notes.css'],
        },
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/social-card.svg',
    // Dark only â€” no light theme, no toggle.
    colorMode: {
      defaultMode: 'dark',
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },
    docs: {
      sidebar: {
        hideable: true,
        autoCollapseCategories: true,
      },
    },
    navbar: {
      title: 'Open',
      logo: {
        alt: 'Open CS Hub',
        src: 'img/logo.svg',
      },
      hideOnScroll: true,
      items: [
        { to: '/', label: 'Home', position: 'left', activeBaseRegex: '^/open/$' },
        { to: '/docs', label: 'Start here', position: 'left' },
        { to: '/playground', label: 'Code Lab', position: 'left' },
        { to: '/apps', label: 'Test Myself', position: 'left' },
        { to: '/practice', label: 'Practice', position: 'left' },
        { to: '/projects', label: 'Projects', position: 'left' },
        { to: '/resources', label: 'Resources', position: 'left' },
        { to: '/cheatsheets', label: 'Cheat Sheets', position: 'left' },
        { to: '/glossary', label: 'Glossary', position: 'left' },
        { to: '/roadmaps', label: 'Roadmaps', position: 'left' },
        { to: '/map', label: 'Map', position: 'left' },
        { to: '/tools', label: 'Tools', position: 'left' },
        { to: '/careers', label: 'Global Career Links', position: 'left' },
        {
          // Opens the Ask AI drawer on the current page â€” no navigation, and
          // no API key, so nothing is ever billed to us.
          type: 'dropdown',
          label: 'Ask AI',
          position: 'left',
          className: 'navbar-ai',
          items: [
            // These open the in-page drawer (see src/theme/Root.tsx), which
            // recognises them by class. They carry href="#" rather than a
            // made-up anchor so the build's anchor checking stays meaningful.
            { href: '#', label: 'ChatGPT', className: 'ai-item ai-chatgpt' },
            { href: '#', label: 'Claude', className: 'ai-item ai-claude' },
            { href: '#', label: 'Perplexity', className: 'ai-item ai-perplexity' },
          ],
        },
        {
          href: 'https://www.linkedin.com/in/sp4532/',
          position: 'right',
          className: 'header-linkedin-link',
          'aria-label': 'LinkedIn profile',
        },
        {
          href: 'https://github.com/Subrata-CS',
          position: 'right',
          className: 'header-github-link',
          'aria-label': 'GitHub profile',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [],
      copyright: `MIT License Â· Â© ${new Date().getFullYear()} Subrata Pramanik`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: [
        'bash',
        'c',
        'cpp',
        'java',
        'python',
        'sql',
        'json',
        'yaml',
        'rust',
        'go',
        'kotlin',
        'docker',
      ],
    },
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 4,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
