/**
 * IMPORTANT: there is deliberately no manual list here.
 *
 * `autogenerated` mode scans the `docs/` folder and builds the sidebar itself,
 * so any new .md file or folder shows up automatically.
 * Ordering comes from the numeric folder prefix and the "position" field
 * in each `_category_.json`.
 */
const sidebars = {
    csSidebar: [
        {
            type: 'autogenerated',
            dirName: '.',
        },
    ],
};
export default sidebars;
