import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * IMPORTANT: ekhane kono manual list nei — eta ICCHA kore.
 *
 * `autogenerated` mode `docs/` folder scan kore sidebar NIJEI banay.
 * Tai notun .md file / notun folder add korlei sidebar-e automatic chole ashe.
 * Order control hoy folder er number prefix ar `_category_.json` er "position" theke.
 */
const sidebars: SidebarsConfig = {
  csSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
