import type { VizKind } from '@site/src/components/Viz';

export type SectionViz = { kind: VizKind; caption: string };

/**
 * Every section slug -> the visualisation that runs behind it.
 * Slugs match the `slug:` front matter generated by tools/generate.py.
 */
export const SECTION_VIZ: Record<string, SectionViz> = {
  'computer-fundamentals': { kind: 'cpu', caption: 'instruction pipeline' },
  'programming-fundamentals': { kind: 'code', caption: 'source compiling' },
  'discrete-mathematics': { kind: 'graph', caption: 'graph traversal' },
  'linear-algebra': { kind: 'matrix', caption: 'matrix product' },
  'probability-and-statistics': { kind: 'scatter', caption: 'sampling · fit' },
  calculus: { kind: 'scatter', caption: 'gradient descent' },
  'data-structures-and-algorithms': { kind: 'graph', caption: 'BFS frontier' },
  'computer-organization-and-architecture': { kind: 'cpu', caption: 'five-stage pipeline' },
  'operating-systems': { kind: 'pipeline', caption: 'process scheduling' },
  'computer-networks': { kind: 'packets', caption: 'packets in flight' },
  'database-systems': { kind: 'database', caption: 'index scan' },
  'software-engineering': { kind: 'pipeline', caption: 'build · test · ship' },
  'git-and-github': { kind: 'pipeline', caption: 'commit pipeline' },
  'web-development': { kind: 'browser', caption: 'render pass' },
  'mobile-development': { kind: 'browser', caption: 'layout pass' },
  'cloud-computing': { kind: 'pipeline', caption: 'deploy rollout' },
  cybersecurity: { kind: 'crypto', caption: 'hash rounds' },
  'compiler-design': { kind: 'code', caption: 'lex · parse · emit' },
  'theory-of-computation': { kind: 'graph', caption: 'state transitions' },
  'distributed-systems': { kind: 'packets', caption: 'consensus messages' },
  'parallel-computing': { kind: 'cpu', caption: 'parallel lanes' },
  'computer-graphics': { kind: 'matrix', caption: 'transform stack' },
  'human-computer-interaction': { kind: 'browser', caption: 'interface flow' },
  'embedded-systems': { kind: 'cpu', caption: 'interrupt cycle' },
  'real-time-systems': { kind: 'pipeline', caption: 'deadline scheduling' },
  'data-science': { kind: 'scatter', caption: 'exploratory analysis' },
  'data-mining': { kind: 'scatter', caption: 'cluster discovery' },
  'information-retrieval': { kind: 'database', caption: 'inverted index lookup' },
  'artificial-intelligence': { kind: 'graph', caption: 'search tree expansion' },
  'machine-learning': { kind: 'scatter', caption: 'fitting the model' },
  'deep-learning': { kind: 'network', caption: 'forward · backward pass' },
  'specialized-ai-fields': { kind: 'network', caption: 'attention heads' },
  mlops: { kind: 'pipeline', caption: 'training pipeline' },
  devops: { kind: 'pipeline', caption: 'CI/CD run' },
  blockchain: { kind: 'crypto', caption: 'block confirmations' },
  'internet-of-things': { kind: 'packets', caption: 'sensor telemetry' },
  robotics: { kind: 'cpu', caption: 'control loop' },
  'quantum-computing': { kind: 'quantum', caption: 'qubit rotation' },
  'research-methodology': { kind: 'code', caption: 'drafting · citing' },
  'advanced-research-areas': { kind: 'network', caption: 'federated rounds' },
};

/** Cycled on the homepage so the front page is always moving. */
export const HOME_CYCLE: SectionViz[] = [
  { kind: 'network', caption: 'deep learning · forward pass' },
  { kind: 'cpu', caption: 'architecture · pipeline' },
  { kind: 'graph', caption: 'algorithms · traversal' },
  { kind: 'scatter', caption: 'machine learning · fit' },
  { kind: 'packets', caption: 'networks · routing' },
  { kind: 'crypto', caption: 'security · hashing' },
];

/** Resolve a pathname such as /open/docs/machine-learning/linear-regression */
export function vizForPath(pathname: string): SectionViz | null {
  const marker = '/docs/';
  const at = pathname.indexOf(marker);
  if (at === -1) return null;
  const slug = pathname.slice(at + marker.length).split('/')[0];
  return SECTION_VIZ[slug] ?? null;
}
